[package]
name = "window_manager"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "window_manager"
path = "main.rs"

[dependencies]
librost = { path = "../../librost" }

[profile.release]
panic = "abort"
lto = true
opt-level = "z"  # Optimize for size
