[package]
name = "rust_os"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uefi_boot"
path = "src/uefi_boot.rs"

[dependencies]
linked_list_allocator = "0.10.5"

[profile.release]
opt-level = 2
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
