[package]
name = "rust_os"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uefi_boot"
path = "src/uefi_boot.rs"

[dependencies]
linked_list_allocator = "0.10.5"
smoltcp = { version = "0.12", default-features = false, features = ["proto-ipv4", "proto-ipv6", "proto-dhcpv4", "proto-dns", "socket-tcp", "socket-udp", "socket-icmp", "socket-raw", "socket-dhcpv4", "socket-dns", "async", "medium-ethernet", "alloc"] }

[profile.release]
opt-level = 2
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
