[package]
name = "librost"
version = "0.1.0"
edition = "2021"

[lib]
name = "librost"
path = "src/lib.rs"

[features]
default = []
image-codecs = ["dep:image_codecs"]

[dependencies]
image_codecs = { path = "../image_codecs", optional = true }
